# config.yaml
defaults:
  - _self_

# General settings
image_path: ./generated_test_image.tif
tile_size: 1024
batch_size: 4
image_size: 10000

# DDP settings
gpus: 1
accelerator: gpu
workers: 4
precision: 16-mixed

# Logging and profiling
log_interval: 10
profiler: simple

